[package]
name = "unarr"
version = "0.1.0"
authors = ["wangxinyu <comicfans44@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.unarr_sys]

#git = "https://github.com/comicfans/unarr_sys"
path = "/home/comicfans/working/unarr_sys"
