[package]
name = "libunarr_rs"
version = "0.1.0"
authors = ["wangxinyu <comicfans44@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.libunarr_sys]

#git = "https://github.com/comicfans/libunarr_sys"
path = "/home/wangxinyu/libunarr_sys"
